#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: killport [port]"
else
  process=$(lsof -i:$1)
  if [ -z "$process" ]; then
    echo "No process found on port $1"
    exit 1
  else
    echo "Process found on port $1:"
    echo "$process"
  fi
  kill -9 $(lsof -t -i:$1)
  if [ $? -eq 0 ]; then
    echo "Killed process on port $1"
  else
    echo "No process found on port $1"
    exit 1
  fi
fi
