# apt install functions — generated by packages/lock-apt-packages.sh
# Copy the functions below into setup.sh (or source this file).
# Do not edit by hand: re-run the generator and it will be overwritten.

# --- not included: base system (present on any Ubuntu install) -------------
#   ca-certificates
#   dash
#   diffutils
#   findutils
#   grep
#   gzip
#   hostname
#   init
#   lsb-release
#   ncurses-base
#   ncurses-bin
#   net-tools
#   python3
#   python3-dbus
#   python3-gi
#   tar
#   ubuntu-minimal

# --- not included: third-party origins (installed by recipes/local debs) ---
#   brave-browser (https://brave-browser-apt-release.s3.brave.com)
#   cloudflared (/var/lib/dpkg/status)
#   code (https://packages.microsoft.com/repos/code)
#   containerd.io (https://download.docker.com/linux/ubuntu)
#   docker-buildx-plugin (https://download.docker.com/linux/ubuntu)
#   docker-ce (https://download.docker.com/linux/ubuntu)
#   docker-ce-cli (https://download.docker.com/linux/ubuntu)
#   docker-compose-plugin (https://download.docker.com/linux/ubuntu)
#   gh (https://cli.github.com/packages)
#   google-cloud-cli (https://packages.cloud.google.com/apt)
#   neovim (/var/lib/dpkg/status)
#   nvidia-container-toolkit (https://nvidia.github.io/libnvidia-container/stable/deb/amd64)

# --- not included: excluded by policy (EXCLUDE_PATTERNS in the generator) ---
#   language-pack-en
#   language-pack-en-base
#   language-pack-gnome-en
#   language-pack-gnome-en-base
#   linux-generic-hwe-24.04
#   linux-headers-7.0.0-27-generic
#   linux-modules-nvidia-595-open-generic-hwe-26.04
#   nvidia-driver-595-open

install_system() {
  local packages=(
    appstream aptitude dkms efibootmgr flatpak gdebi gnupg grub-efi-amd64
    grub-efi-amd64-signed network-manager-openvpn nginx pkexec polkitd
    shim-signed ubuntu-desktop ubuntu-desktop-minimal ubuntu-restricted-addons
    ubuntu-standard ubuntu-wallpapers v4l2loopback-dkms wpasupplicant
  )

  print_info "Installing system packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more system packages."
  fi
}

install_cli_tools() {
  local packages=(
    7zip asciidoc bc btop ccze curl dialog fakeroot fastfetch file fzf
    hashdeep htop hwdata hyphen-en-ca hyphen-en-gb hyphen-en-us
    ibus-table-cangjie-big ibus-table-cangjie3 ibus-table-cangjie5 inxi jq
    libchewing3-data libnotify-bin lnav lzma m17n-db most multitail
    mythes-en-au mythes-en-us pixz plocate pyliblo-utils ranger rar ripgrep
    tmux tree unzip v4l-utils wget wtype zsh zsh-autosuggestions
    zsh-syntax-highlighting
  )

  print_info "Installing cli tools packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more cli tools packages."
  fi
}

install_dev_tools() {
  local packages=(
    autoconf automake autopoint bear blueprint-compiler build-essential clang
    clang-format clang-tools clangd cmake cmake-data desktop-file-utils g++
    g++-aarch64-linux-gnu gawk gcc gcc-aarch64-linux-gnu gettext git git-lfs
    gource ipython3 libtool libtool-bin llvm make meson nasm ninja-build
    pkg-config qtchooser qttools5-dev-tools valac
  )

  print_info "Installing dev tools packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more dev tools packages."
  fi
}

install_dev_libs() {
  local packages=(
    gir1.2-ayatanaappindicator3-0.1 gir1.2-gtk-3.0 gir1.2-gtk-4.0
    libadwaita-1-dev libasound2-dev libavdevice-dev
    libayatana-appindicator3-dev libbz2-dev libcairo2-dev libcmark-dev
    libconfig-dev libconfuse-dev libcurl4-openssl-dev libdbus-1-dev
    libdbusmenu-gtk3-dev libdisplay-info-dev libdmapsharing-4.0-dev libdrm-dev
    libegl-dev libegl1 libegl1-mesa-dev libegl1:i386 libepoxy-dev libev-dev
    libffi-dev libfluidsynth-dev libfontconfig1-dev libfreeimage-dev
    libfreetype-dev libftgl-dev libgbm-dev libgif-dev libgirepository1.0-dev
    libgl-dev libgl1-mesa-dev libgles-dev libgles1 libgles2-mesa-dev
    libglew-dev libglm-dev libglvnd-core-dev libglvnd-dev libgme-dev
    libgtk-3-dev libgtk-4-dev libgtkmm-3.0-dev libinput-dev libiw-dev
    libjpeg-dev libjson-c-dev libjsoncpp-dev libkrb5-dev liblua5.4-dev
    libmpdclient-dev libmpg123-dev libncurses-dev libnl-genl-3-dev
    libopenal-data libopenal-dev libopencv-dev libopengl-dev libpango1.0-dev
    libpcre2-dev libpixman-1-dev libpulse-dev libreadline-dev librsvg2-dev
    libsdl1.2-dev libsdl2-dev libseat-dev libsecret-1-dev libsndfile1-dev
    libssl-dev libswresample-dev libsystemd-dev libunistring-dev libuv1-dev
    libvpx-dev libwebkit2gtk-4.1-dev libwireplumber-0.5-dev libwxbase3.2-1t64
    libwxgtk-webview3.2-dev libwxgtk3.2-1t64 libwxgtk3.2-dev libwxsvg-dev
    libxcb-dri2-0-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev
    libxcb-keysyms1-dev libxcb-present-dev libxcb-randr0-dev libxcb-util-dev
    libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libxkbregistry-dev
    libxml2-dev libyajl-dev libz3-dev lxc-dev mesa-common-dev uthash-dev
    zlib1g-dev
  )

  print_info "Installing dev libs packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more dev libs packages."
  fi
}

install_python() {
  local packages=(
    pipx pyqt5-dev-tools pyqt6-dev-tools python-is-python3 python3-babel
    python3-cairo python3-dev python3-distutils-extra python3-evdev
    python3-gi-cairo python3-matplotlib python3-packaging python3-pip
    python3-pynvim python3-pyqt5 python3-pyqt6 python3-pyudev python3-qtpy
    python3-scipy python3-setuptools python3-sphinx python3-venv python3-xdg
  )

  print_info "Installing python packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more python packages."
  fi
}

install_runtime_libs() {
  local packages=(
    apt-transport-https libchewing3 libm17n-0 libmarisa1 libopencc-data
    libopencc1.1 libotf1 libpinyin-data libpinyin15 thunderbird-locale-en
    thunderbird-locale-en-gb thunderbird-locale-en-us
  )

  print_info "Installing runtime libs packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more runtime libs packages."
  fi
}

install_desktop() {
  local packages=(
    fortune-mod gnome-browser-connector gnome-shell-extension-manager
    gnome-software-plugin-flatpak gnome-tweaks kitty libreoffice-help-common
    libreoffice-help-en-gb libreoffice-help-en-us nautilus-admin
    policykit-1-gnome steam-devices thunar transmission usbview wl-clipboard
    wofi zeal
  )

  print_info "Installing desktop packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more desktop packages."
  fi
}

install_multimedia() {
  local packages=(
    blender ffmpeg imagemagick mypaint notcurses-bin notcurses-data
    pavucontrol playerctl pulseaudio-utils timidity vlc
  )

  print_info "Installing multimedia packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more multimedia packages."
  fi
}

install_virtualization() {
  local packages=(
    cloud-image-utils libguestfs-tools libvirt-clients libvirt-daemon-system
    qemu-system-arm qemu-system-x86 qemu-user qemu-utils virt-manager
    virt-viewer virtinst virtiofsd
  )

  print_info "Installing virtualization packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more virtualization packages."
  fi
}

install_fonts() {
  local packages=(
    fonts-font-awesome ttfautohint
  )

  print_info "Installing fonts packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more fonts packages."
  fi
}

install_locale_docs() {
  local packages=(
    libreoffice-l10n-en-gb libreoffice-l10n-en-za
  )

  print_info "Installing locale docs packages ..."
  if ! sudo debconf-apt-progress -- apt-get install -y "${packages[@]}"; then
    handle_error "Failed to install one or more locale docs packages."
  fi
}

install_wine() {
  print_info "Installing Wine ..."
  sudo apt install -y --install-recommends \
    libwine libwine:i386 wine32:i386 wine64 winetricks ||
    handle_error "Failed to install Wine."
}

